server:
  port: 8080

# mysql db configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/algodomain_task
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

